### ISSUE TITLE
2.2 Epic 2 - Containerization + Acceptance Criteria

### ISSUE THREAD

**Issue by ChrisAbdo** [ChrisAbdo/IS373-Hexo#11]
Description: As a student, I want to access the Containerization article and be able to navigate between the articles.

Acceptance criteria:
- [ ] Be able to access the Containerization article
- [ ] Navigate to other articles
- [ ] Share the article on social media

Tasks:
- [ ] Make sure Containerization article is visible in recent articles
- [ ] Ensure recent articles is populated with other articles
- [ ] make sure each link title redirects to the proper article
