### ISSUE TITLE
1.1 Epic 1 - Architecture Comparison + Acceptance Criteria

### ISSUE THREAD

**Issue by oriyana** [ChrisAbdo/IS373-Hexo#20]
**Description:**  
As a student, I want to understand how Docker containers share the host OS kernel and how this contributes to their lightweight nature. The information should be easily understandable and presentable.

**Acceptance Criteria:**
- [ ] Information about Docker containers using a shared kernel is available.
- [ ] Explanation of how Docker containers are lightweight due to packaging only the application and its dependencies.

**Tasks:**
- [ ] Create a Docker_Containers.md page
- [ ] Include the proper title
- [ ] Ensure information is clear and concise
