### ISSUE TITLE
1.1.2 User Story 2 - Understanding Virtual Machines

### ISSUE THREAD

**Issue by oriyana** [ChrisAbdo/IS373-Hexo#21]
**Description:**  
As a student, I want to understand how Virtual Machines utilize a hypervisor and run a full operating system. The information should be easily understandable and presentable.

**Acceptance Criteria:**
- [ ] Information about VMs running on a hypervisor layer with their own complete OS is available.
- [ ] Explanation of how VMs differ from containers due to their full OS and increased overhead.

**Tasks:**
- [ ] Create a Virtual_Machines.md page
- [ ] Include the proper title
- [ ] Ensure information is clear and concise
