### ISSUE TITLE
1.2 Epic 2 - Performance Comparison + Acceptance Criteria

### ISSUE THREAD

**Issue by oriyana** [ChrisAbdo/IS373-Hexo#22]
**Description:**  
As a student, I want to understand the benefits of Docker's faster startup times and efficient resource usage. The information should be easily understandable and presentable.

**Acceptance Criteria:**
- [ ] Information about Docker containers' near-instant startup times is provided.
- [ ] Details on how Docker containers consume fewer resources and allow for higher density on the host machine.

**Tasks:**
- [ ] Create a Docker_Performance.md page
- [ ] Include the proper title
- [ ] Ensure information is clear and concise
