### ISSUE TITLE
1.2.2 User Story 2 - Virtual Machines' performance drawbacks

### ISSUE THREAD

**Issue by oriyana** [ChrisAbdo/IS373-Hexo#23]
**Description:**  
As a student, I want to understand the performance drawbacks of Virtual Machines, such as longer boot times and higher resource consumption. The information should be easily understandable and presentable.

**Acceptance Criteria:**
- [ ] Information about VMs requiring longer boot times is available.
- [ ] Explanation of how VMs consume more resources compared to containers due to the need to run a full operating system.

**Tasks:**
- [ ] Create a Virtual_Machine_Performance.md page
- [ ] Include the proper title
- [ ] Ensure information is clear and concise
