### ISSUE TITLE
1.1 Epic 1 - Architecture Comparison + Acceptance Criteria

### ISSUE THREAD

**Issue by oriyana** [ChrisAbdo/IS373-Hexo#24]
**Description:**  
As a student, I want to understand the architectural differences between Docker containers and Virtual Machines. This includes understanding the sharing of the host OS kernel by Docker containers and the hypervisor utilization by Virtual Machines.

**Acceptance Criteria:**
- [ ] Information about Docker containers and their architecture is available.
- [ ] Information about Virtual Machines and their architecture is available.

**Tasks:**
- [ ] Create an Architecture_Comparison.md page.
- [ ] Include the overview of Docker containers and Virtual Machines.
- [ ] Ensure all information is clear and concise.
