### ISSUE TITLE
2.1 Epic 1 - WSL2 + Acceptance Criteria

### ISSUE THREAD

**Issue by ChrisAbdo** [ChrisAbdo/IS373-Hexo#8]
Description: 
As a student, I want to access the WSL2 article and be able to navigate between the articles.
The information should be easily understandable and presentable.

Acceptance Criteria:
- [ ] WSL2 article should appear in recent articles
- [ ] Clicking on WSL2 article should redirect to that page

Tasks:
- [ ] Create a WSL2.md page
- [ ] Include the proper title
- [ ] Test to make sure title aligns with page
